Spring:
  application:
    name: Primeiro

  datasource:
    url: jdbc:h2:mem:Produtos
    username: sa
    password: 123
  jpa:
    database-platform : org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console